### PR TITLE
Upgrade DataFusion from 31.0.0 to 40.1.0

### PR DESCRIPTION
**Pull request by andygrove**

### CODE REVIEW

**Comment by andygrove** [comment]
@dandandan fyi - is this all we need to do for upgrading DF version?

**Comment by Dandandan** [comment]
If the code still runs - yes I think so

**Comment by andygrove** [comment]
it worked for me locally, so 🤞

**Comment by andygrove** [comment]
I need to add the new timings ...

**Comment by andygrove** [comment]
I ran into an issue - https://github.com/duckdblabs/db-benchmark/issues/92

**Comment by Dandandan** [comment]
I think @Tmonster runs them once in a while

**Comment by Tmonster** [comment]
Duckdb will be releasing a new version soon, so I will re-run a number of the benchmarks. Will update the datafusion version as well

**Comment by Tmonster** [comment]
closing since the benchmark was just updated with data fusion version 41.0.0. 
@Dandandan @andygrove let me know if there is anything I missed.

**Comment by Dandandan** [comment]
Thanks @Tmonster we probably make a PR soon for DataFusion 42, as many performance improvements were added compared to 41 and DataFusion will perform better for aggregations.

**Pull request closed without merging**
