### PR TITLE
Add Vaex

### PR DESCRIPTION
**Pull request by cosmojg**
This is just a straight merge of the code contributed by the Vaex team in their pull request on the original H2O.ai repository. If it doesn't work out of the box, it's at least a good starting point for incorporating Vaex and facilitating comparisons between it and DuckDB.

### CODE REVIEW

**Comment by Tmonster** [comment]
Thank you for the PR! Will definitely take a look. Do you think you could rebase it on top of this fork? Otherwise the commit history can get kind of muddy

**Review by Tmonster — CHANGES_REQUESTED** [review]
Looking good so far! Can you also add the files/changes to files

`_report/report.R` - modify function `get_report_solutions()`
`_report/history.Rmd` - add the result graphs for veax.
`_benchplot/benchplot-dict.R` - add the colors for veax in the graphs, the queries used for each question, and an empty list for the exceptions.
`veax/setup-vaex.sh` - a simple script to setup and install vaex by hand. Preferably in a virtual env.


You can see an example of these modifications in the PR https://github.com/duckdblabs/db-benchmark/pull/12/files

**Comment by cosmojg** [comment]
Thanks for the review! It might be a while before I get back to this, but hang tight.

**Comment by szarnyasg** [comment]
The Vaex project is [inactive](https://github.com/vaexio/vaex/graphs/contributors), so let's close this.

**Pull request closed without merging**
