### PR TITLE
fix a typo in setup-juliads.sh

### PR DESCRIPTION
**Pull request by sl-solution**

### CODE REVIEW

**Comment by szarnyasg** [comment]
cc @Tmonster

**Comment by Tmonster** [comment]
Hi @sl-solution, if I'm not mistaken the current setup scripts for julia have been updated to 1.9.3. Do you mind if I close this PR?
https://github.com/duckdblabs/db-benchmark/blob/master/juliadf/setup-juliadf.sh
https://github.com/duckdblabs/db-benchmark/blob/master/juliads/setup-juliads.sh

**Comment by sl-solution** [comment]
Julia is updated to 1.9.3, however, the JULIA_HOME variable is not updated in the following file.

> https://github.com/duckdblabs/db-benchmark/blob/master/juliads/setup-juliads.sh

**Comment by sl-solution** [comment]
has been fixed

**Pull request closed without merging**
